api:
  base_url: https://api-v2.solscan.io
  timeout: 30
cookies:
  _ga: GA1.1.1675623496.1756736880
  _ga_PS3V7B7KV0: GS2.1.s1756736880$o1$g0$t1756736882$j58$l0$h0
  auth_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtyaXNobmFnYWlraXNldHN1QGdtYWlsLmNvbSIsImFjdGlvbiI6ImxvZ2dlZCIsImlhdCI6MTc1NjY0MjUyNiwiZXhwIjoxNzY3NDQyNTI2fQ.Ejga0g4G9FHzfJK-ivUyfnWN35Q6LK5yg2X7DiDzK0Y
  cf_clearance: UOB1RaEvNtt8t_TIxjkS31J3PivzBCgFmM6f06MwajI-1756736875-1.2.1.1-GrOHGjTDYG6wnywbjRqhBhPlzcpsJJKlWT8810lvnAb7LDNlfz5qiPjCQdkECOhE8wGcnHWLlH.y18EB26Y6yn7Tv6w2aNg976zJ_0hofEC.rcWCtCN5U4E1FP4CoaVBG8teToz8HrV4FUMU0xxCKNelcdPYrHHp_ZvVX9C1pWFYjj1zuK5YaXYxUq8YqAYfOLudVlEtRkCG7emeo5z2M5f24.9pV7PAEihfZ5GwMUQ
default_params:
  exclude_amount_zero: true
  page_size: 100
  remove_spam: false
headers:
  accept: application/json, text/plain, */*
  accept_encoding: gzip, deflate, br, zstd
  accept_language: en-US,en;q=0.9,zh-HK;q=0.8,zh-CN;q=0.7,zh;q=0.6,es-MX;q=0.5,es;q=0.4,ru-RU;q=0.3,ru;q=0.2
  origin: https://solscan.io
  referer: https://solscan.io/
  sec_ch_ua: '"Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"'
  sec_ch_ua_mobile: ?0
  sec_ch_ua_platform: '"Windows"'
  sec_fetch_dest: empty
  sec_fetch_mode: cors
  sec_fetch_site: same-site
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/139.0.0.0 Safari/537.36
pagination:
  delay_between_pages: 0.5
  max_pages: 100
  retry_failed_pages: 2
proxy:
  enabled: true
  http: http://127.0.0.1:10808
  https: http://127.0.0.1:10808
retry:
  backoff_factor: 1
  max_retries: 3
  status_codes:
  - 429
  - 500
  - 502
  - 503
  - 504
storage:
  directory: storage
  filename_format: solscan_data_{timestamp}.json
target_tokens:
- address: 5zCETicUCJqJ5Z3wbfFPZqtSpHPYqnggs1wX7ZRpump
  description: Illusion of Life
  name: SPARK
  symbol: SPARK
