api:
  base_url: https://api-v2.solscan.io
  timeout: 30
cookies:
  _ga: GA1.1.1458082094.1756908921
  _ga_PS3V7B7KV0: GS2.1.s1756908921$o1$g0$t1756908921$j60$l0$h0
  auth_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtyaXNobmFnYWlraXNldHN1QGdtYWlsLmNvbSIsImFjdGlvbiI6ImxvZ2dlZCIsImlhdCI6MTc1NjY0MjUyNiwiZXhwIjoxNzY3NDQyNTI2fQ.Ejga0g4G9FHzfJK-ivUyfnWN35Q6LK5yg2X7DiDzK0Y
  cf_clearance: GtaqIzqD6890.3lLN.iLHc2AAHdY_NAuAbuiUNcOI6I-1756908914-1.2.1.1-oJp70JR7krXb0ekUC3Sod7cHyI2AicrnOEC0eA6PFSr1xHjI0KtxCBVag_bajcxsPHLse99vRp2bpEsfeGaByZpG3zX7tBGlKPjwSOrvOGAhyXI3qznNfAZD7qbqF5UHQYoAzfldQA2wkhx8HL8GdnRBEbUAApiZXqdxWk50O2G0hmI95dZfHece_OUbSsTCoxmomYI6hV3VDOUaA1LvEbiOe42wE1X2yH0ueciBVBE
default_params:
  exclude_amount_zero: true
  page_size: 100
  remove_spam: false
headers:
  accept: application/json, text/plain, */*
  accept_encoding: gzip, deflate, br, zstd
  accept_language: en-US,en;q=0.9,zh-HK;q=0.8,zh-CN;q=0.7,zh;q=0.6,es-MX;q=0.5,es;q=0.4,ru-RU;q=0.3,ru;q=0.2
  origin: https://solscan.io
  priority: u=1, i
  referer: https://solscan.io/
  sec_ch_ua: '"Chromium";v="140", "Not=A?Brand";v="24", "Google Chrome";v="140"'
  sec_ch_ua_mobile: ?0
  sec_ch_ua_platform: '"Windows"'
  sec_fetch_dest: empty
  sec_fetch_mode: cors
  sec_fetch_site: same-site
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/140.0.0.0 Safari/537.36
pagination:
  delay_between_pages: 0.5
  max_pages: 100
  retry_failed_pages: 2
proxy:
  enabled: true
  http: http://127.0.0.1:10808
  https: http://127.0.0.1:10808
retry:
  backoff_factor: 1
  max_retries: 3
  status_codes:
  - 429
  - 500
  - 502
  - 503
  - 504
storage:
  directory: storage
  filename_format: solscan_data_{timestamp}.json
target_tokens:
- address: 5zCETicUCJqJ5Z3wbfFPZqtSpHPYqnggs1wX7ZRpump
  description: Illusion of Life
  name: SPARK
  symbol: SPARK
